/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.thsolucoes.helpdesk.ui;

import com.thsolucoes.helpdesk.domain.Client;
import com.thsolucoes.helpdesk.domain.Serializer;
import com.thsolucoes.helpdesk.domain.Token;
import com.thsolucoes.helpdesk.services.AuthenticationService;
import com.thsolucoes.helpdesk.services.ClientSessionManager;
import com.thsolucoes.helpdesk.services.HttpService;
import com.thsolucoes.helpdesk.services.JacksonService;
import java.net.http.HttpResponse;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class TokenAuthenticationUI extends javax.swing.JFrame {
    
    private final HttpService HttpServiceHandler;
    private final AuthenticationService AuthenticationServiceHandler;
    private final Serializer serializer;
    private Client client;

    /**
     * Creates new form TokenAuthenticationUI
     */
    public TokenAuthenticationUI() {
        this.HttpServiceHandler = new HttpService("http://localhost:8080");
        this.AuthenticationServiceHandler = new AuthenticationService(this.HttpServiceHandler);
        this.serializer = new JacksonService();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JValidateTokenButton = new javax.swing.JButton();
        JTokenErrorLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTokenField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JCompanyLabel = new javax.swing.JLabel();
        JCompanyOwnerLabel = new javax.swing.JLabel();
        JEnterpriseIdentifierLabel = new javax.swing.JLabel();
        JConfirmDataButton = new javax.swing.JButton();
        JCancelDataButton = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TH Soluções - HelpDesk");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("HelpDesk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Token:");

        JValidateTokenButton.setBackground(new java.awt.Color(0, 153, 255));
        JValidateTokenButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JValidateTokenButton.setForeground(new java.awt.Color(255, 255, 255));
        JValidateTokenButton.setText("VALIDAR");
        JValidateTokenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JValidateTokenButtonActionPerformed(evt);
            }
        });

        JTokenErrorLabel.setForeground(new java.awt.Color(204, 0, 51));
        JTokenErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JTokenErrorLabel.setText("  ");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Informações do Cliente");

        JTokenField.setBackground(new java.awt.Color(204, 204, 204));
        JTokenField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JTokenField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JTokenField.setMaximumSize(new java.awt.Dimension(40, 40));
        JTokenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTokenFieldActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("EMPRESA:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("REPRESENTANTE:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("CNPJ:");

        JCompanyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCompanyLabel.setForeground(new java.awt.Color(102, 102, 102));
        JCompanyLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JCompanyLabel.setText("Nome Fantasia (Razão Social)");

        JCompanyOwnerLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JCompanyOwnerLabel.setForeground(new java.awt.Color(102, 102, 102));
        JCompanyOwnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JCompanyOwnerLabel.setText("Van Gogh");

        JEnterpriseIdentifierLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JEnterpriseIdentifierLabel.setForeground(new java.awt.Color(102, 102, 102));
        JEnterpriseIdentifierLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JEnterpriseIdentifierLabel.setText("XX.XXX.XXX/YYYY-ZZ");

        JConfirmDataButton.setBackground(new java.awt.Color(0, 153, 0));
        JConfirmDataButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JConfirmDataButton.setForeground(new java.awt.Color(255, 255, 255));
        JConfirmDataButton.setText("CONFIRMAR");
        JConfirmDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JConfirmDataButtonActionPerformed(evt);
            }
        });

        JCancelDataButton.setBackground(new java.awt.Color(102, 102, 102));
        JCancelDataButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JCancelDataButton.setForeground(new java.awt.Color(255, 255, 255));
        JCancelDataButton.setText("CANCELAR");
        JCancelDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCancelDataButtonActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        label1.setForeground(new java.awt.Color(102, 102, 102));
        label1.setText("No seu aplicativo ServiceDesk na seção Repositório > Clientes, localize o cliente desejado e selecione-o.");

        label2.setForeground(new java.awt.Color(102, 102, 102));
        label2.setText("Em seguida, identifique o código chamado TOKEN, que consiste em uma sequência de caracteres aleatórios.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTokenField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(JValidateTokenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JEnterpriseIdentifierLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JCompanyLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JCompanyOwnerLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCancelDataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JConfirmDataButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTokenErrorLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 31, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JValidateTokenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTokenField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTokenErrorLabel)
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addComponent(JCompanyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCompanyOwnerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JEnterpriseIdentifierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JCancelDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JConfirmDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTokenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTokenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTokenFieldActionPerformed

    private void JValidateTokenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JValidateTokenButtonActionPerformed
        int length = this.JTokenField.getText().length();
        
        if (length == 0) {
            JOptionPane.showMessageDialog(null, "O campo token é obrigatório; portanto, não pode ser vazio!", "Token Inválido", JOptionPane.ERROR_MESSAGE);
        } else {
            if (length > 40) {
                this.JTokenErrorLabel.setText("O tamanho do token não pode exceder 40 caracteres!");
            } else if (length < 40) {
                this.JTokenErrorLabel.setText("O tamanho do token deve atingir 40 caracteres!");
            } else {
                this.JTokenErrorLabel.setText(" ");
                String tokenFromUI = this.JTokenField.getText();
                String body = this.serializer.serialize(new Token(tokenFromUI));
                HttpResponse response = this.HttpServiceHandler.post("/resources/agent/token", body);
                if (response == null) {
                    JOptionPane.showMessageDialog(null, "Estamos com problemas no servidor. Por favor, aguarde alguns instantes e tente novamente.", "Erro Interno no Servidor", JOptionPane.ERROR_MESSAGE);
                } else if (!(response.statusCode() == 200)) {
                    JOptionPane.showMessageDialog(null, "Não foi possível encontrar nenhum cliente com o token informado. Verifique o token e tente novamente.", "Token Desconhecido", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Tudo certo! Verifique se as informações são as mesmas do cliente desejado, em seguida clique no botão de confirmar.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    Client client = (Client) this.serializer.deserialize((String) response.body(), new Client());
                    this.client = client;
                    this.JCompanyLabel.setText(this.client.company);
                    this.JCompanyOwnerLabel.setText(this.client.owner);
                    this.JEnterpriseIdentifierLabel.setText(this.client.enterpriseIdentifier);
                }
            }
        }
    }//GEN-LAST:event_JValidateTokenButtonActionPerformed

    private void JConfirmDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JConfirmDataButtonActionPerformed
        if (this.JCompanyLabel.getText().equals("Nome Fantasia (Razão Social)")
                || this.JCompanyOwnerLabel.getText().equals("Van Gogh")
                || this.JEnterpriseIdentifierLabel.getText().equals("XX.XXX.XXX/YYYY-ZZ")) {
            JOptionPane.showMessageDialog(null, "Por favor, forneça as informações necessárias para a autenticação.", "Informações Ausentes", JOptionPane.WARNING_MESSAGE);
        } else {
            int option = JOptionPane.showConfirmDialog(null, "Deseja confirmar as informações inseridas?", "Confirmação", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                ClientSessionManager.saveActiveClient(this.client);
                
                HomeUI homeUI = new HomeUI();
                homeUI.setVisible(true);
                StringBuilder builder = new StringBuilder();
                
                builder.append(this.client.company);
                int pointer = builder.indexOf("(", 0);
                
                String firstName = builder.substring(0, pointer - 1);
                homeUI.getJGreetingsLabel().setText("Olá, " + firstName);
                
                this.dispose();
            }
        }

    }//GEN-LAST:event_JConfirmDataButtonActionPerformed

    private void JCancelDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCancelDataButtonActionPerformed
        this.JCompanyLabel.setText("Nome Fantasia (Razão Social)");
        this.JCompanyOwnerLabel.setText("Van Gogh");
        this.JEnterpriseIdentifierLabel.setText("XX.XXX.XXX/YYYY-ZZ");
        JOptionPane.showMessageDialog(null, "As informações foram canceladas com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_JCancelDataButtonActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new TokenAuthenticationUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCancelDataButton;
    private javax.swing.JLabel JCompanyLabel;
    private javax.swing.JLabel JCompanyOwnerLabel;
    private javax.swing.JButton JConfirmDataButton;
    private javax.swing.JLabel JEnterpriseIdentifierLabel;
    private javax.swing.JLabel JTokenErrorLabel;
    private javax.swing.JTextField JTokenField;
    private javax.swing.JButton JValidateTokenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}                 

